sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: ${SKY_ALIOSS_ENDPOINT}
    access-key-id: ${SKY_ALIOSS_ACCESS_KEY_ID}
    access-key-secret: ${SKY_ALIOSS_ACCESS_KEY_SECRET}
    bucket-name: ${SKY_ALIOSS_BUCKET_NAME}
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: ${SKY_WECHAT_APPID}
    secret: ${SKY_WECHAT_SECRET}
    mchid: ${SKY_WECHAT_MCHID}
    mchSerialNo: ${SKY_WECHAT_MCHSERIALNO}
    privateKeyFilePath: ${SKY_WECHAT_PRIVATEKEYFILEPATH}
    apiV3Key: ${SKY_WECHAT_APIV3KEY}
    weChatPayCertFilePath: ${SKY_WECHAT_WECHATPAYCERTFILEPATH}
    notifyUrl: ${SKY_WECHAT_NOTIFYURL}
    refundNotifyUrl: ${SKY_WECHAT_REFUNDNOTIFYURL}
  shop:
    address: 北京市海淀区上地十街
  baidu:
    ak: 123